steps:  
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: mvn
    args: ['--version']
    
  - name: maven:3.6.0-jdk-11-slim
    dir: microservices-config-server/
    entrypoint: mvn
    args: ['clean','deploy','-Dmaven.test.skip=true']